apiVersion: apps/v1
kind: Deployment
metadata:
  name: myportfolio-api-deployment
  labels:
    app: myportfolio-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myportfolio-api
  template:
    metadata:
      labels:
        app: myportfolio-api
    spec:
      containers:
      - name: myportfolio-api
        image: 989298484874.dkr.ecr.ap-northeast-1.amazonaws.com/myportfolio:b2aafa48a425f3ebf8bccf427e787528f9691a2e
        ports:
        - containerPort: 8080
